import {
	LinearClient as LinearSdkClient,
	type Issue as LinearSdkIssue,
	type IssueLabel as LinearSdkIssueLabel,
	type WorkflowState as LinearSdkWorkflowState,
} from "@linear/sdk";
import { normalizeIssueKey } from "../core/state";
import type {
	LinearIssue,
	PlannedSplitTask,
	ResolvedProjectConfig,
	WorkflowStage,
} from "../core/types";

type WorkflowLabelStage = keyof ResolvedProjectConfig["linear"]["labelMap"];

interface LinearLabelRecord {
	id: string;
	name: string;
	teamId?: string;
}

interface ParentIssueRef {
	id: string;
	key: string;
	title: string;
	url: string;
	teamId?: string;
}

interface CreatedLinearIssueRef {
	id: string;
	identifier: string;
	title: string;
	url: string;
}

interface TodoIssueFromPlanInput {
	title: string;
	description: string;
	stateId: string;
	teamId: string;
	parentId: string;
	projectId?: string;
	priority?: number;
}

export function buildSplitTaskIssueTitle(
	parentIssueKey: string,
	taskTitle: string,
): string {
	const normalizedParentKey = normalizeIssueKey(parentIssueKey);
	const normalizedTitle = taskTitle.trim() || "Untitled split task";
	const upperTitle = normalizedTitle.toUpperCase();
	const upperKey = normalizedParentKey.toUpperCase();
	const bracketPrefix = `[${upperKey}]`;
	if (
		upperTitle.startsWith(bracketPrefix) ||
		upperTitle.startsWith(`${upperKey}:`) ||
		upperTitle.startsWith(`${upperKey} -`)
	) {
		return normalizedTitle;
	}
	return `[${normalizedParentKey}] ${normalizedTitle}`;
}

export function buildSplitTaskIssueDescription(input: {
	task: PlannedSplitTask;
	parentIssue: ParentIssueRef;
}): string {
	const summary =
		input.task.description?.trim() || "No task summary provided by planner.";
	const plannerLabels = input.task.labels
		?.map((label) => label.trim())
		.filter((label) => label.length > 0);
	const metadataLines = [
		plannerLabels && plannerLabels.length > 0
			? `Labels: ${plannerLabels.join(", ")}`
			: undefined,
		typeof input.task.priority === "number"
			? `Priority: ${input.task.priority}`
			: undefined,
	].filter((line): line is string => Boolean(line));
	const parentTitle = input.parentIssue.title.trim();

	return [
		"Task summary:",
		summary,
		"",
		"Parent issue:",
		`${input.parentIssue.key}: ${parentTitle}`,
		input.parentIssue.url,
		...(metadataLines.length > 0
			? ["", "Planner metadata:", ...metadataLines]
			: []),
		"",
		"Source:",
		"Generated by ADHD.ai planning decomposition.",
	].join("\n");
}

export function buildTodoIssueFromPlanInput(input: {
	task: PlannedSplitTask;
	parentIssue: ParentIssueRef;
	assignedStateId: string;
	teamId: string;
	projectId?: string;
}): TodoIssueFromPlanInput {
	return {
		title: buildSplitTaskIssueTitle(input.parentIssue.key, input.task.title),
		description: buildSplitTaskIssueDescription({
			task: input.task,
			parentIssue: input.parentIssue,
		}),
		stateId: input.assignedStateId,
		teamId: input.teamId,
		parentId: input.parentIssue.id,
		projectId: input.projectId,
		priority: input.task.priority,
	};
}

export function resolveSplitTaskTeamId(
	configuredTeamId: string | undefined,
	parentIssueTeamId: string | undefined,
): string {
	const teamId = configuredTeamId?.trim() || parentIssueTeamId?.trim();
	if (!teamId) {
		throw new Error(
			"Cannot create split Linear tasks because neither linear.teamId nor the parent issue team id is available.",
		);
	}
	return teamId;
}

export class LinearClient {
	private readonly client: LinearSdkClient;
	private resolvedStatusMap:
		| ResolvedProjectConfig["linear"]["statusMap"]
		| null = null;
	private resolvedCanceledStateId: string | null = null;
	private resolvedWorkflowLabelIds: Partial<
		Record<WorkflowLabelStage, string>
	> = {};
	private workflowLabelIds: string[] = [];
	private workflowLabelsResolved = false;

	constructor(private readonly config: ResolvedProjectConfig) {
		this.client = new LinearSdkClient({
			apiKey: config.linear.apiKey,
			apiUrl: config.linear.apiUrl,
		});
	}

	async fetchWork(issueArg?: string): Promise<LinearIssue[]> {
		await this.ensureResolvedStatusMap();

		if (issueArg) {
			const issue = await this.fetchIssueByIdentifier(issueArg);
			if (!issue) {
				return [];
			}
			return isIssueInConfiguredProject(
				issue.projectId,
				this.config.linear.projectId,
			)
				? [issue]
				: [];
		}

		const viewer = await this.client.viewer;
		const assignedIssues = await viewer.assignedIssues({
			first: this.config.linear.pollLimit,
		});
		const includeLabels = Boolean(this.config.linear.requiredLabel);
		const issues = await Promise.all(
			assignedIssues.nodes.map((issue) =>
				this.mapSdkIssueToLinearIssue(issue, includeLabels),
			),
		);
		const assignedStateId = this.requiredStatusMap().assigned;

		return sortIssuesByPriority(
			issues
				.filter((issue) =>
					isIssueInConfiguredProject(
						issue.projectId,
						this.config.linear.projectId,
					),
				)
				.filter((issue) => issue.state.id === assignedStateId)
				.filter((issue) => {
					if (!this.config.linear.requiredLabel) {
						return true;
					}
					return issue.labels.some(
						(label) =>
							label.name.toLowerCase() ===
							this.config.linear.requiredLabel?.toLowerCase(),
					);
				}),
		);
	}

	async fetchIssueByIdentifier(issueArg: string): Promise<LinearIssue | null> {
		return this.findIssueByIdentifier(normalizeIssueKey(issueArg));
	}

	async fetchReviewOnlyWork(): Promise<LinearIssue[]> {
		await this.ensureResolvedStatusMap();
		const viewer = await this.client.viewer;
		const assignedIssues = await viewer.assignedIssues({
			first: this.config.linear.pollLimit,
		});
		const reviewStateIds = new Set([
			this.requiredStatusMap().pr_created,
			this.requiredStatusMap().reviewing,
			this.requiredStatusMap().testing,
		]);
		const testingLabelName = this.config.linear.labelMap.testing?.trim();
		const issues = await Promise.all(
			assignedIssues.nodes.map((issue) =>
				this.mapSdkIssueToLinearIssue(issue, true),
			),
		);
		return sortIssuesByPriority(
			issues
				.filter((issue) =>
					isIssueInConfiguredProject(
						issue.projectId,
						this.config.linear.projectId,
					),
				)
				.filter((issue) =>
					isLinearIssueReviewOnlyCandidate(
						issue,
						reviewStateIds,
						testingLabelName,
					),
				),
		);
	}

	async isAssignedState(stateId: string): Promise<boolean> {
		await this.ensureResolvedStatusMap();
		return this.requiredStatusMap().assigned === stateId;
	}

	async markStage(
		issueId: string,
		stage: keyof ResolvedProjectConfig["linear"]["statusMap"],
	): Promise<void> {
		await this.ensureResolvedStatusMap();
		if (this.config.dryRun) {
			return;
		}
		const stateId = this.requiredStatusMap()[stage];
		await this.client.updateIssue(issueId, { stateId });
	}

	async markCanceled(issueId: string): Promise<void> {
		if (this.config.dryRun) {
			return;
		}
		await this.ensureResolvedStatusMap();
		const stateId = await this.resolveCanceledStateId();
		await this.client.updateIssue(issueId, { stateId });
	}

	async createTodoIssueFromPlan(
		parentIssue: ParentIssueRef,
		task: PlannedSplitTask,
	): Promise<CreatedLinearIssueRef> {
		const teamId = await this.resolveTeamIdForSplitTask(parentIssue);
		const assignedStateId = await this.resolveAssignedStateIdForTeam(teamId);

		const createInput = buildTodoIssueFromPlanInput({
			task,
			parentIssue,
			assignedStateId,
			teamId,
			projectId: this.config.linear.projectId,
		});
		if (this.config.dryRun) {
			return {
				id: `dry-run-${normalizeIssueKey(parentIssue.key)}-${Date.now()}`,
				identifier: `${normalizeIssueKey(parentIssue.key)}-SPLIT`,
				title: createInput.title,
				url: `${parentIssue.url}#split-task`,
			};
		}

		const payload = await this.client.createIssue(createInput as never);
		if (!payload.success) {
			throw new Error(
				`Failed to create split Linear task '${task.title}' for ${parentIssue.key}.`,
			);
		}

		const createdIssue =
			(await payload.issue) ??
			(payload.issueId ? await this.client.issue(payload.issueId) : undefined);
		if (!createdIssue?.id || !createdIssue.identifier || !createdIssue.url) {
			throw new Error(
				`Split Linear task '${task.title}' was created without required issue fields.`,
			);
		}

		const labelIds = await this.resolveSplitTaskLabelIds(task.labels);
		if (labelIds.length > 0) {
			await this.client.updateIssue(createdIssue.id, {
				addedLabelIds: labelIds,
			});
		}

		return {
			id: createdIssue.id,
			identifier: createdIssue.identifier,
			title: createdIssue.title,
			url: createdIssue.url,
		};
	}

	async applyStageLabel(issueId: string, stage: WorkflowStage): Promise<void> {
		if (!isWorkflowLabelStage(stage)) {
			return;
		}
		await this.ensureResolvedWorkflowLabels();
		const nextLabelId = this.resolvedWorkflowLabelIds[stage];
		if (!nextLabelId || this.config.dryRun) {
			return;
		}

		const currentLabelIds = await this.fetchIssueLabelIds(issueId);
		const currentLabelSet = new Set(currentLabelIds);
		const removedLabelIds = this.workflowLabelIds.filter(
			(labelId) => labelId !== nextLabelId && currentLabelSet.has(labelId),
		);
		const addedLabelIds = currentLabelSet.has(nextLabelId) ? [] : [nextLabelId];

		if (addedLabelIds.length === 0 && removedLabelIds.length === 0) {
			return;
		}

		await this.client.updateIssue(issueId, {
			addedLabelIds,
			removedLabelIds,
		});
	}

	async comment(issueId: string, body: string): Promise<void> {
		if (this.config.dryRun) {
			return;
		}
		await this.client.createComment({ issueId, body });
	}

	private async findIssueByIdentifier(
		identifier: string,
	): Promise<LinearIssue | null> {
		let issue: LinearSdkIssue | undefined;
		try {
			issue = await this.client.issue(identifier);
		} catch (error) {
			const message =
				error instanceof Error ? error.message.toLowerCase() : String(error);
			if (
				message.includes("not found") ||
				message.includes("invalid") ||
				message.includes("does not exist")
			) {
				return null;
			}
			throw error;
		}
		if (!issue) {
			return null;
		}
		return this.mapSdkIssueToLinearIssue(issue, true);
	}

	private async resolveTeamIdForSplitTask(
		parentIssue: ParentIssueRef,
	): Promise<string> {
		const configuredTeamId = this.config.linear.teamId?.trim();
		if (configuredTeamId) {
			return configuredTeamId;
		}

		const parentTeamId = parentIssue.teamId?.trim();
		if (parentTeamId) {
			return parentTeamId;
		}

		const refreshedParent = await this.findIssueByIdentifier(parentIssue.key);
		return resolveSplitTaskTeamId(undefined, refreshedParent?.teamId);
	}

	private async resolveAssignedStateIdForTeam(teamId: string): Promise<string> {
		const configuredTeamId = this.config.linear.teamId?.trim();
		if (configuredTeamId && configuredTeamId === teamId) {
			await this.ensureResolvedStatusMap();
			return this.requiredStatusMap().assigned;
		}

		const assignedStatus = this.config.linear.statusMap.assigned.trim();
		if (isLikelyUuid(assignedStatus)) {
			return assignedStatus;
		}

		const workflowStates = await this.client.workflowStates({
			first: 250,
		});
		const states = workflowStates.nodes.filter(
			(state) => state.teamId === teamId,
		);
		return this.resolveStatusValue("assigned", assignedStatus, states);
	}

	private async ensureResolvedStatusMap(): Promise<void> {
		if (this.resolvedStatusMap) {
			return;
		}

		const workflowStates = await this.client.workflowStates({
			first: 250,
		});
		const states = workflowStates.nodes.filter((state) =>
			this.config.linear.teamId
				? state.teamId === this.config.linear.teamId
				: true,
		);

		const statusMap = this.config.linear.statusMap;
		this.resolvedStatusMap = {
			assigned: this.resolveStatusValue("assigned", statusMap.assigned, states),
			planning: this.resolveStatusValue("planning", statusMap.planning, states),
			implementing: this.resolveStatusValue(
				"implementing",
				statusMap.implementing,
				states,
			),
			pr_created: this.resolveStatusValue(
				"pr_created",
				statusMap.pr_created,
				states,
			),
			reviewing: this.resolveStatusValue(
				"reviewing",
				statusMap.reviewing,
				states,
			),
			testing: this.resolveStatusValue("testing", statusMap.testing, states),
			blocked: this.resolveStatusValue("blocked", statusMap.blocked, states),
			done: this.resolveStatusValue("done", statusMap.done, states),
		};
	}

	private async resolveCanceledStateId(): Promise<string> {
		if (this.resolvedCanceledStateId) {
			return this.resolvedCanceledStateId;
		}

		const workflowStates = await this.client.workflowStates({
			first: 250,
		});
		const states = workflowStates.nodes.filter((state) =>
			this.config.linear.teamId
				? state.teamId === this.config.linear.teamId
				: true,
		);
		const canceled = states.find(
			(state) => state.name.toLowerCase() === "canceled",
		);

		if (canceled?.id) {
			this.resolvedCanceledStateId = canceled.id;
			return canceled.id;
		}

		// Fallback for customized workflows without a literal "Canceled" state name.
		this.resolvedCanceledStateId = this.requiredStatusMap().blocked;
		return this.resolvedCanceledStateId;
	}

	private async ensureResolvedWorkflowLabels(): Promise<void> {
		if (this.workflowLabelsResolved) {
			return;
		}

		const configuredEntries = Object.entries(
			this.config.linear.labelMap,
		).filter(([, labelName]) => Boolean(labelName?.trim())) as Array<
			[WorkflowLabelStage, string]
		>;

		if (configuredEntries.length === 0) {
			this.resolvedWorkflowLabelIds = {};
			this.workflowLabelIds = [];
			this.workflowLabelsResolved = true;
			return;
		}

		const labelsConnection = await this.client.issueLabels({
			first: 250,
		});
		const availableLabels = labelsConnection.nodes.map((label) =>
			this.mapSdkLabelToRecord(label),
		);
		const resolved: Partial<Record<WorkflowLabelStage, string>> = {};

		for (const [stage, labelNameRaw] of configuredEntries) {
			const labelName = labelNameRaw.trim();
			let labelId = this.findLabelIdByName(labelName, availableLabels);
			if (!labelId) {
				if (!this.config.linear.autoCreateLabels) {
					throw new Error(
						`Linear label '${labelName}' for stage '${stage}' was not found in project '${this.config.id}'.`,
					);
				}
				const created = await this.createIssueLabel(labelName);
				labelId = created.id;
				availableLabels.push(created);
			}
			resolved[stage] = labelId;
		}

		this.resolvedWorkflowLabelIds = resolved;
		this.workflowLabelIds = Array.from(
			new Set(
				Object.values(resolved).filter(
					(labelId): labelId is string => typeof labelId === "string",
				),
			),
		);
		this.workflowLabelsResolved = true;
	}

	private findLabelIdByName(
		labelName: string,
		labels: LinearLabelRecord[],
	): string | undefined {
		const matches = labels.filter(
			(label) => label.name.toLowerCase() === labelName.toLowerCase(),
		);
		if (matches.length === 0) {
			return undefined;
		}
		if (this.config.linear.teamId) {
			const teamMatch = matches.find(
				(label) => label.teamId === this.config.linear.teamId,
			);
			if (teamMatch) {
				return teamMatch.id;
			}
			const workspaceLabel = matches.find((label) => !label.teamId);
			if (workspaceLabel) {
				return workspaceLabel.id;
			}
		}
		return matches[0]?.id;
	}

	private async createIssueLabel(
		labelName: string,
	): Promise<LinearLabelRecord> {
		const payload = await this.client.createIssueLabel({
			name: labelName,
			teamId: this.config.linear.teamId,
		});
		if (!payload.success) {
			throw new Error(`Failed to create Linear label '${labelName}'.`);
		}

		const issueLabel =
			(await payload.issueLabel) ??
			(payload.issueLabelId
				? await this.client.issueLabel(payload.issueLabelId)
				: undefined);
		if (!issueLabel?.id) {
			throw new Error(`Linear label '${labelName}' was created without an id.`);
		}
		return this.mapSdkLabelToRecord(issueLabel);
	}

	private async resolveSplitTaskLabelIds(
		labelNames: string[] | undefined,
	): Promise<string[]> {
		const normalizedNames = (labelNames ?? [])
			.map((label) => label.trim())
			.filter(Boolean);
		if (normalizedNames.length === 0) {
			return [];
		}

		const labelsConnection = await this.client.issueLabels({
			first: 250,
		});
		const availableLabels = labelsConnection.nodes.map((label) =>
			this.mapSdkLabelToRecord(label),
		);
		const labelIds: string[] = [];

		for (const labelName of normalizedNames) {
			let labelId = this.findLabelIdByName(labelName, availableLabels);
			if (!labelId) {
				if (!this.config.linear.autoCreateLabels) {
					throw new Error(
						`Linear label '${labelName}' was not found for split task in project '${this.config.id}'.`,
					);
				}
				const created = await this.createIssueLabel(labelName);
				availableLabels.push(created);
				labelId = created.id;
			}
			labelIds.push(labelId);
		}

		return Array.from(new Set(labelIds));
	}

	private resolveStatusValue(
		key: keyof ResolvedProjectConfig["linear"]["statusMap"],
		value: string,
		states: LinearSdkWorkflowState[],
	): string {
		const trimmed = value.trim();
		if (isLikelyUuid(trimmed)) {
			return trimmed;
		}
		const found = states.find(
			(state) => state.name.toLowerCase() === trimmed.toLowerCase(),
		);
		if (!found) {
			throw new Error(
				`Unable to resolve Linear status '${trimmed}' for '${key}' in project '${this.config.id}'.`,
			);
		}
		return found.id;
	}

	private requiredStatusMap(): ResolvedProjectConfig["linear"]["statusMap"] {
		if (!this.resolvedStatusMap) {
			throw new Error("Linear status map is not resolved");
		}
		return this.resolvedStatusMap;
	}

	private async mapSdkIssueToLinearIssue(
		issue: LinearSdkIssue,
		includeLabels: boolean,
	): Promise<LinearIssue> {
		const state = await issue.state;
		const project = await issue.project;
		if (!state?.id) {
			throw new Error(
				`Issue ${issue.identifier} is missing workflow state data.`,
			);
		}
		const labels = includeLabels
			? (await issue.labels()).nodes.map((label) => ({
					id: label.id,
					name: label.name,
				}))
			: [];
		return {
			id: issue.id,
			identifier: issue.identifier,
			title: issue.title,
			description: issue.description?.trim() || undefined,
			url: issue.url,
			projectId: project?.id ?? undefined,
			teamId: issue.teamId ?? undefined,
			priority: {
				value: issue.priority ?? 0,
				name: issue.priorityLabel ?? "No priority",
			},
			state: {
				id: state.id,
				name: state.name,
			},
			labels,
		};
	}

	private async fetchIssueLabelIds(issueId: string): Promise<string[]> {
		const issue = await this.client.issue(issueId);
		if (!issue) {
			return [];
		}
		const labels = await issue.labels();
		return labels.nodes
			.map((label) => label.id)
			.filter((id): id is string => Boolean(id));
	}

	private mapSdkLabelToRecord(label: LinearSdkIssueLabel): LinearLabelRecord {
		return {
			id: label.id,
			name: label.name,
			teamId: label.teamId ?? undefined,
		};
	}
}

function isLikelyUuid(value: string): boolean {
	return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
		value,
	);
}

function isWorkflowLabelStage(
	stage: WorkflowStage,
): stage is WorkflowLabelStage {
	return stage === "pr_created" || stage === "reviewing" || stage === "testing";
}

const PRIORITY_SORT_ORDER: Record<number, number> = {
	1: 0,
	2: 1,
	3: 2,
	4: 3,
	0: 4,
};

function getPriorityRank(priority: number): number {
	return PRIORITY_SORT_ORDER[priority] ?? PRIORITY_SORT_ORDER[0];
}

export function sortIssuesByPriority(issues: LinearIssue[]): LinearIssue[] {
	return issues
		.map((issue, index) => ({ issue, index }))
		.sort((left, right) => {
			const rankDiff =
				getPriorityRank(left.issue.priority.value) -
				getPriorityRank(right.issue.priority.value);
			if (rankDiff !== 0) {
				return rankDiff;
			}
			return left.index - right.index;
		})
		.map((entry) => entry.issue);
}

export function isLinearIssueReviewOnlyCandidate(
	issue: LinearIssue,
	reviewStateIds: Set<string>,
	testingLabelName?: string,
): boolean {
	if (reviewStateIds.has(issue.state.id)) {
		return true;
	}
	if (!testingLabelName) {
		return false;
	}
	return issue.labels.some(
		(label) => label.name.toLowerCase() === testingLabelName.toLowerCase(),
	);
}

export function isIssueInConfiguredProject(
	issueProjectId: string | undefined,
	configuredProjectId: string | undefined,
): boolean {
	if (!configuredProjectId) {
		return true;
	}
	return issueProjectId === configuredProjectId;
}
