import { createRequire } from "node:module";
import type {
	LinearIssue,
	PlannedSplitTask,
	ResolvedProjectConfig,
	WorkflowStage,
} from "../../core/types";
import { normalizeIssueKey } from "../../features/workflow/state";
import type {
	BacklogTaskInput,
	BacklogTaskIssueInput,
	BuildTodoIssueInput,
	CreatedLinearIssueRef,
	LinearLabelRecord,
	LinearStatusStage,
	ParentIssueRef,
	SplitTaskIssueDescriptionInput,
	TodoIssueFromPlanInput,
	WorkflowLabelStage,
	WorkflowLabelUpdate,
} from "./linear.types";

type LinearSdkWorkflowState = {
	id: string;
	name: string;
	teamId?: string | null;
};

type LinearSdkTeam = {
	id: string;
	name?: string | null;
	key?: string | null;
};

type LinearSdkProject = {
	id: string;
	teams: () => Promise<{ nodes: LinearSdkTeam[] }>;
};

type LinearSdkIssueLabel = {
	id: string;
	name: string;
	teamId?: string | null;
};

type LinearSdkIssue = {
	id: string;
	identifier: string;
	title: string;
	description?: string | null;
	url: string;
	teamId?: string | null;
	priority?: number | null;
	priorityLabel?: string | null;
	project: Promise<{ id?: string | null } | null>;
	state: Promise<{ id: string; name: string } | null>;
	creator: Promise<{ id?: string | null } | null>;
	assignee: Promise<{ id?: string | null } | null>;
	labels: () => Promise<{ nodes: LinearSdkIssueLabel[] }>;
};

type LinearSdkClientInstance = {
	viewer: Promise<{
		assignedIssues: (input: { first: number }) => Promise<{
			nodes: LinearSdkIssue[];
		}>;
	}>;
	issue: (identifier: string) => Promise<LinearSdkIssue | undefined>;
	project: (id: string) => Promise<LinearSdkProject | undefined>;
	updateIssue: (
		issueId: string,
		input: Record<string, unknown>,
	) => Promise<unknown>;
	createIssue: (input: Record<string, unknown>) => Promise<{
		success: boolean;
		issueId?: string | null;
		issue?: Promise<LinearSdkIssue | null>;
	}>;
	createComment: (input: {
		issueId: string;
		body: string;
	}) => Promise<unknown>;
	workflowStates: (input: { first: number }) => Promise<{
		nodes: LinearSdkWorkflowState[];
	}>;
	issueLabels: (input: { first: number }) => Promise<{
		nodes: LinearSdkIssueLabel[];
	}>;
	createIssueLabel: (input: {
		name: string;
		teamId?: string;
	}) => Promise<{
		success: boolean;
		issueLabelId?: string | null;
		issueLabel?: Promise<LinearSdkIssueLabel | null>;
	}>;
	issueLabel: (id: string) => Promise<LinearSdkIssueLabel | null>;
};

type LinearSdkClientCtor = new (input: {
	apiKey: string;
	apiUrl?: string;
}) => LinearSdkClientInstance;

const require = createRequire(import.meta.url);

const LINEAR_MAX_REQUESTS_PER_HOUR = 1800;
const LINEAR_REQUEST_INTERVAL_MS = Math.ceil(
	(60 * 60 * 1000) / LINEAR_MAX_REQUESTS_PER_HOUR,
);
const LINEAR_RATE_LIMIT_FALLBACK_DELAY_MS = 60 * 1000;
const LINEAR_RATE_LIMIT_RETRY_DELAYS_MS = [
	LINEAR_RATE_LIMIT_FALLBACK_DELAY_MS,
	2 * LINEAR_RATE_LIMIT_FALLBACK_DELAY_MS,
	5 * LINEAR_RATE_LIMIT_FALLBACK_DELAY_MS,
];

let linearRequestTail: Promise<void> = Promise.resolve();
let nextLinearRequestAt = 0;

export function buildSplitTaskIssueTitle(
	parentIssueKey: string,
	taskTitle: string,
): string {
	const normalizedParentKey = normalizeIssueKey(parentIssueKey);
	const normalizedTitle = taskTitle.trim() || "Untitled split task";
	const upperTitle = normalizedTitle.toUpperCase();
	const upperKey = normalizedParentKey.toUpperCase();
	const bracketPrefix = `[${upperKey}]`;
	if (
		upperTitle.startsWith(bracketPrefix) ||
		upperTitle.startsWith(`${upperKey}:`) ||
		upperTitle.startsWith(`${upperKey} -`)
	) {
		return normalizedTitle;
	}
	return `[${normalizedParentKey}] ${normalizedTitle}`;
}

export function buildSplitTaskIssueDescription(
	input: SplitTaskIssueDescriptionInput,
): string {
	const summary =
		input.task.description?.trim() || "No task summary provided by planner.";
	const plannerLabels = input.task.labels
		?.map((label) => label.trim())
		.filter((label) => label.length > 0);
	const metadataLines = [
		plannerLabels && plannerLabels.length > 0
			? `Labels: ${plannerLabels.join(", ")}`
			: undefined,
		typeof input.task.priority === "number"
			? `Priority: ${input.task.priority}`
			: undefined,
	].filter((line): line is string => Boolean(line));
	const parentTitle = input.parentIssue.title.trim();

	return [
		"Task summary:",
		summary,
		"",
		"Parent issue:",
		`${input.parentIssue.key}: ${parentTitle}`,
		input.parentIssue.url,
		...(metadataLines.length > 0
			? ["", "Planner metadata:", ...metadataLines]
			: []),
		"",
		"Source:",
		"Generated by ADHD.ai planning decomposition.",
	].join("\n");
}

export function buildTodoIssueFromPlanInput(
	input: BuildTodoIssueInput,
): TodoIssueFromPlanInput {
	const projectId = input.parentIssue.projectId?.trim() || input.projectId;
	const assigneeId = input.parentIssue.creatorId?.trim();
	return {
		title: buildSplitTaskIssueTitle(input.parentIssue.key, input.task.title),
		description: buildSplitTaskIssueDescription({
			task: input.task,
			parentIssue: input.parentIssue,
		}),
		stateId: input.assignedStateId,
		teamId: input.teamId,
		parentId: input.parentIssue.id,
		...(projectId ? { projectId } : {}),
		...(assigneeId ? { assigneeId } : {}),
		priority: input.task.priority,
	};
}

export function buildBacklogTaskIssueInput(
	input: BacklogTaskInput & {
		backlogStateId: string;
		teamId: string;
		projectId?: string;
	},
): BacklogTaskIssueInput {
	const projectId = input.projectId?.trim();
	return {
		title: input.title,
		description: input.description,
		stateId: input.backlogStateId,
		teamId: input.teamId,
		...(projectId ? { projectId } : {}),
	};
}

export function resolveSplitTaskTeamId(
	configuredTeamId: string | undefined,
	parentIssueTeamId: string | undefined,
): string {
	const teamId = configuredTeamId?.trim() || parentIssueTeamId?.trim();
	if (!teamId) {
		throw new Error(
			"Cannot create split Linear tasks because neither linear.teamId nor the parent issue team id is available.",
		);
	}
	return teamId;
}

export class LinearClient {
	private readonly client: LinearSdkClientInstance;
	private resolvedStatusMap:
		| ResolvedProjectConfig["linear"]["statusMap"]
		| null = null;
	private resolvedCanceledStateId: string | null = null;
	private resolvedWorkflowLabelIds: Partial<
		Record<WorkflowLabelStage, string>
	> = {};
	private workflowLabelIds: string[] = [];
	private workflowLabelsResolved = false;
	private workflowStatesCache: LinearSdkWorkflowState[] | null = null;
	private issueLabelsCache: LinearLabelRecord[] | null = null;

	constructor(private readonly config: ResolvedProjectConfig) {
		const LinearSdkClient = resolveLinearSdkClient();
		this.client = new LinearSdkClient({
			apiKey: config.linear.apiKey,
			apiUrl: config.linear.apiUrl,
		});
	}

	async fetchWork(issueArg?: string): Promise<LinearIssue[]> {
		await this.ensureResolvedStatusMap();

		if (issueArg) {
			const issue = await this.fetchIssueByIdentifier(issueArg);
			if (!issue) {
				return [];
			}
			return isIssueInConfiguredProject(
				issue.projectId,
				this.config.linear.projectId,
			)
				? [issue]
				: [];
		}

		const viewer = await this.linearRequest(
			async () => (await this.getClient()).viewer,
		);
		const assignedIssues = await this.linearRequest(() =>
			viewer.assignedIssues({
				first: this.config.linear.pollLimit,
			}),
		);
		const includeLabels = Boolean(this.config.linear.requiredLabel);
		const issues = await Promise.all(
			assignedIssues.nodes.map((issue) =>
				this.mapSdkIssueToLinearIssue(issue, includeLabels, false),
			),
		);
		const assignedStateId = this.requiredStatusMap().assigned;

		return sortIssuesByPriority(
			issues
				.filter((issue) =>
					isIssueInConfiguredProject(
						issue.projectId,
						this.config.linear.projectId,
					),
				)
				.filter((issue) => issue.state.id === assignedStateId)
				.filter((issue) => {
					if (!this.config.linear.requiredLabel) {
						return true;
					}
					return issue.labels.some(
						(label) =>
							label.name.toLowerCase() ===
							this.config.linear.requiredLabel?.toLowerCase(),
					);
				}),
		);
	}

	async fetchIssueByIdentifier(issueArg: string): Promise<LinearIssue | null> {
		return this.findIssueByIdentifier(normalizeIssueKey(issueArg));
	}

	async fetchReviewOnlyWork(): Promise<LinearIssue[]> {
		await this.ensureResolvedStatusMap();
		const viewer = await this.linearRequest(
			async () => (await this.getClient()).viewer,
		);
		const assignedIssues = await this.linearRequest(() =>
			viewer.assignedIssues({
				first: this.config.linear.pollLimit,
			}),
		);
		const reviewStateIds = new Set([
			this.requiredStatusMap().pr_created,
			this.requiredStatusMap().reviewing,
			this.requiredStatusMap().testing,
			this.requiredStatusMap().done,
		]);
		const testingLabelName = this.config.linear.labelMap.testing?.trim();
		const issues = await Promise.all(
			assignedIssues.nodes.map((issue) =>
				this.mapSdkIssueToLinearIssue(issue, true, false),
			),
		);
		return sortIssuesByPriority(
			issues
				.filter((issue) =>
					isIssueInConfiguredProject(
						issue.projectId,
						this.config.linear.projectId,
					),
				)
				.filter((issue) =>
					isLinearIssueReviewOnlyCandidate(
						issue,
						reviewStateIds,
						testingLabelName,
					),
				),
		);
	}

	async isAssignedState(stateId: string): Promise<boolean> {
		await this.ensureResolvedStatusMap();
		return this.requiredStatusMap().assigned === stateId;
	}

	async markStage(issueId: string, stage: LinearStatusStage): Promise<void> {
		await this.ensureResolvedStatusMap();
		if (this.config.dryRun) {
			return;
		}
		const statusMap = this.requiredStatusMap();
		if (
			shouldSkipDoneStageRegression(
				await this.fetchIssueStateId(issueId),
				stage,
				statusMap.done,
			)
		) {
			return;
		}
		const stateId = statusMap[stage];
		await this.linearRequest(async () =>
			(await this.getClient()).updateIssue(issueId, { stateId }),
		);
	}

	async markCanceled(issueId: string): Promise<void> {
		if (this.config.dryRun) {
			return;
		}
		await this.ensureResolvedStatusMap();
		if (await this.isIssueDone(issueId)) {
			return;
		}
		const stateId = await this.resolveCanceledStateId();
		await this.linearRequest(async () =>
			(await this.getClient()).updateIssue(issueId, { stateId }),
		);
	}

	async updateIssueDetails(
		issueId: string,
		title: string,
		description: string,
	): Promise<void> {
		if (this.config.dryRun) {
			return;
		}
		await this.linearRequest(async () =>
			(await this.getClient()).updateIssue(issueId, {
				title,
				description,
			}),
		);
	}

	async createBacklogTask(
		input: BacklogTaskInput,
	): Promise<CreatedLinearIssueRef> {
		const teamId = await this.resolveBacklogTaskTeamId();
		const backlogStateId = await this.resolveBacklogStateIdForTeam(teamId);
		const createInput = buildBacklogTaskIssueInput({
			title: input.title,
			description: input.description,
			backlogStateId,
			teamId,
			projectId: this.config.linear.projectId,
		});
		if (this.config.dryRun) {
			const slug = input.title
				.toLowerCase()
				.replace(/[^a-z0-9]+/g, "-")
				.replace(/^-+|-+$/g, "")
				.slice(0, 40);
			return {
				id: `dry-run-backlog-${Date.now()}`,
				identifier: "DRY-RUN-BACKLOG",
				title: createInput.title,
				url: `https://linear.example/dry-run/${slug || "task"}`,
			};
		}

		const payload = await this.linearRequest(async () =>
			(await this.getClient()).createIssue(createInput),
		);
		if (!payload.success) {
			throw new Error(`Failed to create Linear backlog task '${input.title}'.`);
		}
		const createdIssue =
			(await this.linearRequest(() => payload.issue)) ??
			(payload.issueId
				? await this.linearRequest(async () =>
						(await this.getClient()).issue(payload.issueId as string),
					)
				: undefined);
		if (!createdIssue?.id || !createdIssue.identifier || !createdIssue.url) {
			throw new Error(
				`Linear backlog task '${input.title}' was created without required issue fields.`,
			);
		}
		return {
			id: createdIssue.id,
			identifier: createdIssue.identifier,
			title: createdIssue.title,
			url: createdIssue.url,
		};
	}

	async createTodoIssueFromPlan(
		parentIssue: ParentIssueRef,
		task: PlannedSplitTask,
	): Promise<CreatedLinearIssueRef> {
		const hydratedParentIssue =
			await this.hydrateSplitTaskParentIssue(parentIssue);
		const teamId = await this.resolveTeamIdForSplitTask(hydratedParentIssue);
		const assignedStateId = await this.resolveAssignedStateIdForTeam(teamId);

		const createInput = buildTodoIssueFromPlanInput({
			task,
			parentIssue: hydratedParentIssue,
			assignedStateId,
			teamId,
			projectId: this.config.linear.projectId,
		});
		if (this.config.dryRun) {
			return {
				id: `dry-run-${normalizeIssueKey(hydratedParentIssue.key)}-${Date.now()}`,
				identifier: `${normalizeIssueKey(hydratedParentIssue.key)}-SPLIT`,
				title: createInput.title,
				url: `${hydratedParentIssue.url}#split-task`,
			};
		}

		const payload = await this.linearRequest(async () =>
			(await this.getClient()).createIssue(createInput as never),
		);
		if (!payload.success) {
			throw new Error(
				`Failed to create split Linear task '${task.title}' for ${parentIssue.key}.`,
			);
		}

		const createdIssueId = payload.issueId;
		const createdIssue =
			(await this.linearRequest(() => payload.issue)) ??
			(createdIssueId
				? await this.linearRequest(async () =>
						(await this.getClient()).issue(createdIssueId),
					)
				: undefined);
		if (!createdIssue?.id || !createdIssue.identifier || !createdIssue.url) {
			throw new Error(
				`Split Linear task '${task.title}' was created without required issue fields.`,
			);
		}

		const labelIds = await this.resolveSplitTaskLabelIds(task.labels);
		if (labelIds.length > 0) {
			await this.linearRequest(async () =>
				(await this.getClient()).updateIssue(createdIssue.id, {
					addedLabelIds: labelIds,
				}),
			);
		}

		return {
			id: createdIssue.id,
			identifier: createdIssue.identifier,
			title: createdIssue.title,
			url: createdIssue.url,
		};
	}

	async applyStageLabel(issueId: string, stage: WorkflowStage): Promise<void> {
		if (!isWorkflowLabelStage(stage)) {
			return;
		}
		await this.ensureResolvedWorkflowLabels();
		const nextLabelId = this.resolvedWorkflowLabelIds[stage];
		if (!nextLabelId || this.config.dryRun) {
			return;
		}

		const currentLabelIds = await this.fetchIssueLabelIds(issueId);
		const { addedLabelIds, removedLabelIds } = buildWorkflowLabelUpdate(
			currentLabelIds,
			this.workflowLabelIds,
			nextLabelId,
		);

		if (addedLabelIds.length === 0 && removedLabelIds.length === 0) {
			return;
		}

		await this.linearRequest(async () =>
			(await this.getClient()).updateIssue(issueId, {
				addedLabelIds,
				removedLabelIds,
			}),
		);
	}

	async clearWorkflowStageLabels(issueId: string): Promise<void> {
		await this.ensureResolvedWorkflowLabels();
		if (this.config.dryRun || this.workflowLabelIds.length === 0) {
			return;
		}

		const currentLabelIds = await this.fetchIssueLabelIds(issueId);
		const { removedLabelIds } = buildWorkflowLabelUpdate(
			currentLabelIds,
			this.workflowLabelIds,
		);
		if (removedLabelIds.length === 0) {
			return;
		}

		await this.linearRequest(async () =>
			(await this.getClient()).updateIssue(issueId, {
				removedLabelIds,
			}),
		);
	}

	async comment(issueId: string, body: string): Promise<void> {
		if (this.config.dryRun) {
			return;
		}
		await this.linearRequest(async () =>
			(await this.getClient()).createComment({ issueId, body }),
		);
	}

	private async findIssueByIdentifier(
		identifier: string,
	): Promise<LinearIssue | null> {
		let issue: LinearSdkIssue | undefined;
		try {
			issue = await this.linearRequest(async () =>
				(await this.getClient()).issue(identifier),
			);
		} catch (error) {
			const message =
				error instanceof Error ? error.message.toLowerCase() : String(error);
			if (
				message.includes("not found") ||
				message.includes("invalid") ||
				message.includes("does not exist")
			) {
				return null;
			}
			throw error;
		}
		if (!issue) {
			return null;
		}
		return this.mapSdkIssueToLinearIssue(issue, true);
	}

	private async resolveTeamIdForSplitTask(
		parentIssue: ParentIssueRef,
	): Promise<string> {
		const configuredTeamId = this.config.linear.teamId?.trim();
		if (configuredTeamId) {
			return configuredTeamId;
		}

		const parentTeamId = parentIssue.teamId?.trim();
		if (parentTeamId) {
			return parentTeamId;
		}

		const refreshedParent = await this.findIssueByIdentifier(parentIssue.key);
		return resolveSplitTaskTeamId(undefined, refreshedParent?.teamId);
	}

	private async resolveBacklogTaskTeamId(): Promise<string> {
		const configuredTeamId = this.config.linear.teamId?.trim();
		if (configuredTeamId) {
			return configuredTeamId;
		}

		const projectTeamId = await this.resolveBacklogTaskTeamIdFromProject();
		if (projectTeamId) {
			return projectTeamId;
		}

		return this.resolveBacklogTaskTeamIdFromBacklogState();
	}

	private async resolveBacklogTaskTeamIdFromProject(): Promise<
		string | undefined
	> {
		const projectId = this.config.linear.projectId?.trim();
		if (!projectId) {
			return undefined;
		}
		const project = await this.linearRequest(async () =>
			(await this.getClient()).project(projectId),
		);
		const teams = project
			? (await this.linearRequest(() => project.teams())).nodes
			: [];
		const teamIds = uniqueTrimmed(teams.map((team) => team.id));
		if (teamIds.length === 1) {
			return teamIds[0];
		}
		if (teamIds.length > 1) {
			throw new Error(
				`Cannot create Linear backlog task for project '${this.config.id}' because linear.projectId '${projectId}' is attached to multiple teams: ${teamIds.join(", ")}. Set linear.teamId to choose one.`,
			);
		}
		return undefined;
	}

	private async resolveBacklogTaskTeamIdFromBacklogState(): Promise<string> {
		const backlogStatus = this.config.linear.statusMap.backlog.trim();
		const states = await this.fetchWorkflowStates();
		const matchingStates = isLikelyUuid(backlogStatus)
			? states.filter((state) => state.id === backlogStatus)
			: states.filter(
					(state) => state.name.toLowerCase() === backlogStatus.toLowerCase(),
				);
		const teamIds = uniqueTrimmed(matchingStates.map((state) => state.teamId));
		if (teamIds.length === 1) {
			return teamIds[0];
		}
		if (teamIds.length > 1) {
			throw new Error(
				`Cannot create Linear backlog task for project '${this.config.id}' because backlog status '${backlogStatus}' exists for multiple teams: ${teamIds.join(", ")}. Set linear.teamId to choose one.`,
			);
		}
		throw new Error(
			`Cannot create Linear backlog task for project '${this.config.id}' because linear.teamId is not configured and no team could be inferred from linear.projectId or backlog status '${backlogStatus}'. Set linear.teamId to choose a team.`,
		);
	}

	private async resolveBacklogStateIdForTeam(teamId: string): Promise<string> {
		const configuredTeamId = this.config.linear.teamId?.trim();
		if (configuredTeamId && configuredTeamId === teamId) {
			await this.ensureResolvedStatusMap();
			return this.requiredStatusMap().backlog;
		}

		const backlogStatus = this.config.linear.statusMap.backlog.trim();
		if (isLikelyUuid(backlogStatus)) {
			return backlogStatus;
		}

		const states = (await this.fetchWorkflowStates()).filter(
			(state) => state.teamId === teamId,
		);
		return this.resolveStatusValue("backlog", backlogStatus, states);
	}

	private async hydrateSplitTaskParentIssue(
		parentIssue: ParentIssueRef,
	): Promise<ParentIssueRef> {
		if (
			parentIssue.projectId?.trim() &&
			parentIssue.teamId?.trim() &&
			parentIssue.creatorId?.trim()
		) {
			return parentIssue;
		}

		const refreshedParent = await this.findIssueByIdentifier(parentIssue.key);
		if (!refreshedParent) {
			return parentIssue;
		}

		return {
			...parentIssue,
			projectId: parentIssue.projectId ?? refreshedParent.projectId,
			teamId: parentIssue.teamId ?? refreshedParent.teamId,
			creatorId: parentIssue.creatorId ?? refreshedParent.creatorId,
			assigneeId: parentIssue.assigneeId ?? refreshedParent.assigneeId,
		};
	}

	private async resolveAssignedStateIdForTeam(teamId: string): Promise<string> {
		const configuredTeamId = this.config.linear.teamId?.trim();
		if (configuredTeamId && configuredTeamId === teamId) {
			await this.ensureResolvedStatusMap();
			return this.requiredStatusMap().assigned;
		}

		const assignedStatus = this.config.linear.statusMap.assigned.trim();
		if (isLikelyUuid(assignedStatus)) {
			return assignedStatus;
		}

		const states = (await this.fetchWorkflowStates()).filter(
			(state) => state.teamId === teamId,
		);
		return this.resolveStatusValue("assigned", assignedStatus, states);
	}

	private async ensureResolvedStatusMap(): Promise<void> {
		if (this.resolvedStatusMap) {
			return;
		}

		const states = (await this.fetchWorkflowStates()).filter((state) =>
			this.config.linear.teamId
				? state.teamId === this.config.linear.teamId
				: true,
		);

		const statusMap = this.config.linear.statusMap;
		this.resolvedStatusMap = {
			backlog: this.resolveStatusValue("backlog", statusMap.backlog, states),
			assigned: this.resolveStatusValue("assigned", statusMap.assigned, states),
			planning: this.resolveStatusValue("planning", statusMap.planning, states),
			implementing: this.resolveStatusValue(
				"implementing",
				statusMap.implementing,
				states,
			),
			pr_created: this.resolveStatusValue(
				"pr_created",
				statusMap.pr_created,
				states,
			),
			reviewing: this.resolveStatusValue(
				"reviewing",
				statusMap.reviewing,
				states,
			),
			testing: this.resolveStatusValue("testing", statusMap.testing, states),
			blocked: this.resolveStatusValue("blocked", statusMap.blocked, states),
			done: this.resolveStatusValue("done", statusMap.done, states),
		};
	}

	private async resolveCanceledStateId(): Promise<string> {
		if (this.resolvedCanceledStateId) {
			return this.resolvedCanceledStateId;
		}

		const states = (await this.fetchWorkflowStates()).filter((state) =>
			this.config.linear.teamId
				? state.teamId === this.config.linear.teamId
				: true,
		);
		const canceled = states.find(
			(state) => state.name.toLowerCase() === "canceled",
		);

		if (canceled?.id) {
			this.resolvedCanceledStateId = canceled.id;
			return canceled.id;
		}

		// Fallback for customized workflows without a literal "Canceled" state name.
		this.resolvedCanceledStateId = this.requiredStatusMap().blocked;
		return this.resolvedCanceledStateId;
	}

	private async ensureResolvedWorkflowLabels(): Promise<void> {
		if (this.workflowLabelsResolved) {
			return;
		}

		const configuredEntries = Object.entries(
			this.config.linear.labelMap,
		).filter(([, labelName]) => Boolean(labelName?.trim())) as Array<
			[WorkflowLabelStage, string]
		>;

		if (configuredEntries.length === 0) {
			this.resolvedWorkflowLabelIds = {};
			this.workflowLabelIds = [];
			this.workflowLabelsResolved = true;
			return;
		}

		const availableLabels = await this.fetchIssueLabels();
		const resolved: Partial<Record<WorkflowLabelStage, string>> = {};

		for (const [stage, labelNameRaw] of configuredEntries) {
			const labelName = labelNameRaw.trim();
			let labelId = this.findLabelIdByName(labelName, availableLabels);
			if (!labelId) {
				if (!this.config.linear.autoCreateLabels) {
					throw new Error(
						`Linear label '${labelName}' for stage '${stage}' was not found in project '${this.config.id}'.`,
					);
				}
				const created = await this.createIssueLabel(labelName);
				labelId = created.id;
				availableLabels.push(created);
			}
			resolved[stage] = labelId;
		}

		this.resolvedWorkflowLabelIds = resolved;
		this.workflowLabelIds = Array.from(
			new Set(
				Object.values(resolved).filter(
					(labelId): labelId is string => typeof labelId === "string",
				),
			),
		);
		this.workflowLabelsResolved = true;
	}

	private findLabelIdByName(
		labelName: string,
		labels: LinearLabelRecord[],
	): string | undefined {
		const matches = labels.filter(
			(label) => label.name.toLowerCase() === labelName.toLowerCase(),
		);
		if (matches.length === 0) {
			return undefined;
		}
		if (this.config.linear.teamId) {
			const teamMatch = matches.find(
				(label) => label.teamId === this.config.linear.teamId,
			);
			if (teamMatch) {
				return teamMatch.id;
			}
			const workspaceLabel = matches.find((label) => !label.teamId);
			if (workspaceLabel) {
				return workspaceLabel.id;
			}
		}
		return matches[0]?.id;
	}

	private async createIssueLabel(
		labelName: string,
	): Promise<LinearLabelRecord> {
		const payload = await this.linearRequest(async () =>
			(await this.getClient()).createIssueLabel({
				name: labelName,
				teamId: this.config.linear.teamId,
			}),
		);
		if (!payload.success) {
			throw new Error(`Failed to create Linear label '${labelName}'.`);
		}

		const issueLabelId = payload.issueLabelId;
		const issueLabel =
			(await this.linearRequest(() => payload.issueLabel)) ??
			(issueLabelId
				? await this.linearRequest(async () =>
						(await this.getClient()).issueLabel(issueLabelId),
					)
				: undefined);
		if (!issueLabel?.id) {
			throw new Error(`Linear label '${labelName}' was created without an id.`);
		}
		return this.mapSdkLabelToRecord(issueLabel);
	}

	private async resolveSplitTaskLabelIds(
		labelNames: string[] | undefined,
	): Promise<string[]> {
		const normalizedNames = (labelNames ?? [])
			.map((label) => label.trim())
			.filter(Boolean);
		if (normalizedNames.length === 0) {
			return [];
		}

		const availableLabels = await this.fetchIssueLabels();
		const labelIds: string[] = [];

		for (const labelName of normalizedNames) {
			let labelId = this.findLabelIdByName(labelName, availableLabels);
			if (!labelId) {
				if (!this.config.linear.autoCreateLabels) {
					throw new Error(
						`Linear label '${labelName}' was not found for split task in project '${this.config.id}'.`,
					);
				}
				const created = await this.createIssueLabel(labelName);
				availableLabels.push(created);
				labelId = created.id;
			}
			labelIds.push(labelId);
		}

		return Array.from(new Set(labelIds));
	}

	private resolveStatusValue(
		key: keyof ResolvedProjectConfig["linear"]["statusMap"],
		value: string,
		states: LinearSdkWorkflowState[],
	): string {
		const trimmed = value.trim();
		if (isLikelyUuid(trimmed)) {
			return trimmed;
		}
		const found = states.find(
			(state) => state.name.toLowerCase() === trimmed.toLowerCase(),
		);
		if (!found) {
			throw new Error(
				`Unable to resolve Linear status '${trimmed}' for '${key}' in project '${this.config.id}'.`,
			);
		}
		return found.id;
	}

	private requiredStatusMap(): ResolvedProjectConfig["linear"]["statusMap"] {
		if (!this.resolvedStatusMap) {
			throw new Error("Linear status map is not resolved");
		}
		return this.resolvedStatusMap;
	}

	private async fetchWorkflowStates(): Promise<LinearSdkWorkflowState[]> {
		if (this.workflowStatesCache) {
			return this.workflowStatesCache;
		}
		const workflowStates = await this.linearRequest(async () =>
			(await this.getClient()).workflowStates({
				first: 250,
			}),
		);
		const nodes = workflowStates.nodes;
		this.workflowStatesCache = nodes;
		return nodes;
	}

	private async fetchIssueLabels(): Promise<LinearLabelRecord[]> {
		if (this.issueLabelsCache) {
			return this.issueLabelsCache;
		}
		const labelsConnection = await this.linearRequest(async () =>
			(await this.getClient()).issueLabels({
				first: 250,
			}),
		);
		const labels = labelsConnection.nodes.map((label) =>
			this.mapSdkLabelToRecord(label),
		);
		this.issueLabelsCache = labels;
		return labels;
	}

	private async isIssueDone(issueId: string): Promise<boolean> {
		return (
			(await this.fetchIssueStateId(issueId)) === this.requiredStatusMap().done
		);
	}

	private async mapSdkIssueToLinearIssue(
		issue: LinearSdkIssue,
		includeLabels: boolean,
		includeActorRefs = true,
	): Promise<LinearIssue> {
		const state = await this.linearRequest(() => issue.state);
		const project = await this.linearRequest(() => issue.project);
		const creator = includeActorRefs
			? await this.linearRequest(() => issue.creator)
			: undefined;
		const assignee = includeActorRefs
			? await this.linearRequest(() => issue.assignee)
			: undefined;
		if (!state?.id) {
			throw new Error(
				`Issue ${issue.identifier} is missing workflow state data.`,
			);
		}
		const labels = includeLabels
			? (await this.linearRequest(() => issue.labels())).nodes.map((label) => ({
					id: label.id,
					name: label.name,
				}))
			: [];
		return {
			id: issue.id,
			identifier: issue.identifier,
			title: issue.title,
			description: issue.description?.trim() || undefined,
			url: issue.url,
			projectId: project?.id ?? undefined,
			teamId: issue.teamId ?? undefined,
			creatorId: creator?.id ?? undefined,
			assigneeId: assignee?.id ?? undefined,
			priority: {
				value: issue.priority ?? 0,
				name: issue.priorityLabel ?? "No priority",
			},
			state: {
				id: state.id,
				name: state.name,
			},
			labels,
		};
	}

	private async fetchIssueLabelIds(issueId: string): Promise<string[]> {
		const issue = await this.linearRequest(async () =>
			(await this.getClient()).issue(issueId),
		);
		if (!issue) {
			return [];
		}
		const labels = await this.linearRequest(() => issue.labels());
		return labels.nodes
			.map((label) => label.id)
			.filter((id): id is string => Boolean(id));
	}

	private async fetchIssueStateId(
		issueId: string,
	): Promise<string | undefined> {
		const issue = await this.linearRequest(async () =>
			(await this.getClient()).issue(issueId),
		);
		if (!issue) {
			return undefined;
		}
		const state = await this.linearRequest(() => issue.state);
		return state?.id;
	}

	private async linearRequest<T>(
		operation: () => T | PromiseLike<T>,
	): Promise<T> {
		return runLinearRequest(operation);
	}

	private async getClient(): Promise<{
		viewer: PromiseLike<{
			assignedIssues(input: { first: number }): PromiseLike<{
				nodes: LinearSdkIssue[];
			}>;
		}>;
		updateIssue(issueId: string, input: unknown): PromiseLike<unknown>;
		project(projectId: string): PromiseLike<LinearSdkProject | undefined>;
		createIssue(input: unknown): PromiseLike<{
			success: boolean;
			issueId?: string;
			issue?: PromiseLike<LinearSdkIssue | undefined>;
		}>;
		issue(issueId: string): PromiseLike<LinearSdkIssue | undefined>;
		createIssueLabel(input: {
			name: string;
			teamId?: string;
		}): PromiseLike<{
			success: boolean;
			issueLabelId?: string;
			issueLabel?: PromiseLike<LinearSdkIssueLabel | undefined>;
		}>;
		issueLabel(
			issueLabelId: string,
		): PromiseLike<LinearSdkIssueLabel | undefined>;
		createComment(input: {
			issueId: string;
			body: string;
		}): PromiseLike<unknown>;
		workflowStates(input: { first: number }): PromiseLike<{
			nodes: LinearSdkWorkflowState[];
		}>;
		issueLabels(input: { first: number }): PromiseLike<{
			nodes: LinearSdkIssueLabel[];
		}>;
	}> {
		return this.client as Awaited<ReturnType<LinearClient["getClient"]>>;
	}

	private mapSdkLabelToRecord(label: LinearSdkIssueLabel): LinearLabelRecord {
		return {
			id: label.id,
			name: label.name,
			teamId: label.teamId ?? undefined,
		};
	}
}

function resolveLinearSdkClient(): LinearSdkClientCtor {
	try {
		const loaded = require("@linear/sdk") as {
			LinearClient?: LinearSdkClientCtor;
		};
		if (typeof loaded.LinearClient !== "function") {
			throw new Error("missing LinearClient export");
		}
		return loaded.LinearClient;
	} catch (error) {
		const detail = error instanceof Error ? error.message : String(error);
		throw new Error(
			`Failed to load '@linear/sdk'. Install project dependencies before running Linear-integrated commands. ${detail}`,
		);
	}
}

async function runLinearRequest<T>(
	operation: () => T | PromiseLike<T>,
): Promise<T> {
	const run = linearRequestTail.then(async () => {
		const delayMs = nextLinearRequestAt - Date.now();
		if (delayMs > 0) {
			await sleep(delayMs);
		}
		nextLinearRequestAt = Date.now() + LINEAR_REQUEST_INTERVAL_MS;
		return retryLinearRequest(operation);
	});
	linearRequestTail = run.then(
		() => undefined,
		() => undefined,
	);
	return run;
}

async function retryLinearRequest<T>(
	operation: () => T | PromiseLike<T>,
): Promise<T> {
	for (let attempt = 0; ; attempt += 1) {
		try {
			return await operation();
		} catch (error) {
			if (
				!isLinearRateLimitError(error) ||
				attempt >= LINEAR_RATE_LIMIT_RETRY_DELAYS_MS.length
			) {
				throw error;
			}
			const delayMs =
				resolveLinearRateLimitDelayMs(error) ??
				LINEAR_RATE_LIMIT_RETRY_DELAYS_MS[attempt] ??
				LINEAR_RATE_LIMIT_FALLBACK_DELAY_MS;
			await sleep(delayMs);
			nextLinearRequestAt = Math.max(
				nextLinearRequestAt,
				Date.now() + LINEAR_REQUEST_INTERVAL_MS,
			);
		}
	}
}

function sleep(ms: number): Promise<void> {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

export function isLinearRateLimitError(error: unknown): boolean {
	const status = readErrorStatus(error);
	if (status === 429) {
		return true;
	}
	const message = readErrorMessage(error).toLowerCase();
	return (
		message.includes("rate limit") ||
		message.includes("too many requests") ||
		message.includes("429")
	);
}

export function resolveLinearRateLimitDelayMs(
	error: unknown,
): number | undefined {
	const retryAfterMs = readRetryAfterMs(error);
	if (retryAfterMs !== undefined) {
		return retryAfterMs;
	}
	const rateLimitWindowMs = readRateLimitWindowDelayMs(error);
	if (rateLimitWindowMs !== undefined) {
		return rateLimitWindowMs;
	}
	return isLinearRateLimitError(error)
		? LINEAR_RATE_LIMIT_FALLBACK_DELAY_MS
		: undefined;
}

function readRateLimitWindowDelayMs(error: unknown): number | undefined {
	const message = readErrorMessage(error).toLowerCase();
	const match = message.match(/\bper\s+(\d+)\s+(second|minute|hour|day)s?\b/);
	if (!match) {
		return undefined;
	}
	const amount = Number(match[1]);
	if (!Number.isInteger(amount) || amount <= 0) {
		return undefined;
	}
	const unit = match[2];
	if (unit === "second") {
		return amount * 1000;
	}
	if (unit === "minute") {
		return amount * 60 * 1000;
	}
	if (unit === "hour") {
		return amount * 60 * 60 * 1000;
	}
	return amount * 24 * 60 * 60 * 1000;
}

function readErrorStatus(error: unknown): number | undefined {
	const record = asRecord(error);
	const status = record?.status ?? asRecord(record?.response)?.status;
	return typeof status === "number" ? status : undefined;
}

function readRetryAfterMs(error: unknown): number | undefined {
	const headers = asRecord(asRecord(error)?.response)?.headers;
	const retryAfter = readHeader(headers, "retry-after");
	if (!retryAfter) {
		return undefined;
	}
	const seconds = Number(retryAfter);
	if (Number.isFinite(seconds)) {
		return Math.max(0, seconds * 1000);
	}
	const retryAtMs = Date.parse(retryAfter);
	if (!Number.isNaN(retryAtMs)) {
		return Math.max(0, retryAtMs - Date.now());
	}
	return undefined;
}

function readHeader(headers: unknown, name: string): string | undefined {
	if (!headers) {
		return undefined;
	}
	const maybeGet = asRecord(headers)?.get;
	if (typeof maybeGet === "function") {
		const value = maybeGet.call(headers, name);
		return typeof value === "string" ? value : undefined;
	}
	const record = asRecord(headers);
	const direct = record?.[name] ?? record?.[name.toLowerCase()];
	return typeof direct === "string" ? direct : undefined;
}

function readErrorMessage(error: unknown): string {
	if (error instanceof Error) {
		return error.message;
	}
	return String(error);
}

function asRecord(value: unknown): Record<string, unknown> | undefined {
	return value && typeof value === "object"
		? (value as Record<string, unknown>)
		: undefined;
}

function isLikelyUuid(value: string): boolean {
	return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
		value,
	);
}

function uniqueTrimmed(values: Array<string | null | undefined>): string[] {
	return Array.from(
		new Set(values.map((value) => value?.trim()).filter(Boolean)),
	) as string[];
}

function isWorkflowLabelStage(
	stage: WorkflowStage,
): stage is WorkflowLabelStage {
	return stage === "pr_created" || stage === "reviewing" || stage === "testing";
}

const PRIORITY_SORT_ORDER: Record<number, number> = {
	1: 0,
	2: 1,
	3: 2,
	4: 3,
	0: 4,
};

function getPriorityRank(priority: number): number {
	return PRIORITY_SORT_ORDER[priority] ?? PRIORITY_SORT_ORDER[0];
}

export function sortIssuesByPriority(issues: LinearIssue[]): LinearIssue[] {
	return issues
		.map((issue, index) => ({ issue, index }))
		.sort((left, right) => {
			const rankDiff =
				getPriorityRank(left.issue.priority.value) -
				getPriorityRank(right.issue.priority.value);
			if (rankDiff !== 0) {
				return rankDiff;
			}
			return left.index - right.index;
		})
		.map((entry) => entry.issue);
}

export function isLinearIssueReviewOnlyCandidate(
	issue: LinearIssue,
	reviewStateIds: Set<string>,
	testingLabelName?: string,
): boolean {
	if (reviewStateIds.has(issue.state.id)) {
		return true;
	}
	if (!testingLabelName) {
		return false;
	}
	return issue.labels.some(
		(label) => label.name.toLowerCase() === testingLabelName.toLowerCase(),
	);
}

export function shouldSkipDoneStageRegression(
	currentStateId: string | undefined,
	nextStage: LinearStatusStage,
	doneStateId: string,
): boolean {
	return currentStateId === doneStateId && nextStage !== "done";
}

export function buildWorkflowLabelUpdate(
	currentLabelIds: string[],
	workflowLabelIds: string[],
	nextLabelId?: string,
): WorkflowLabelUpdate {
	const currentLabelSet = new Set(currentLabelIds);
	const removedLabelIds = workflowLabelIds.filter(
		(labelId) => labelId !== nextLabelId && currentLabelSet.has(labelId),
	);
	const addedLabelIds =
		nextLabelId && !currentLabelSet.has(nextLabelId) ? [nextLabelId] : [];

	return { addedLabelIds, removedLabelIds };
}

export function isIssueInConfiguredProject(
	issueProjectId: string | undefined,
	configuredProjectId: string | undefined,
): boolean {
	if (!configuredProjectId) {
		return true;
	}
	return issueProjectId === configuredProjectId;
}
