import type { SimulationCase } from "./cli-command-executor-simulation.types";

export const CLI_COMMAND_SIMULATION_MATRIX: SimulationCase[] = [
	{
		name: "run action with all supported optional flags",
		request: {
			action: "run",
			projectId: "default",
			issueKey: "ROY-122",
			poll: true,
			noExitWhenIdle: true,
			concurrency: 2,
			pollIntervalMs: 2500,
			maxPollCycles: 4,
			isolatedWorktrees: true,
		},
		expectedArgs: [
			"devos",
			"run",
			"--project",
			"default",
			"--issue",
			"ROY-122",
			"--poll",
			"--no-exit-when-idle",
			"--concurrency",
			"2",
			"--poll-interval-ms",
			"2500",
			"--max-poll-cycles",
			"4",
			"--isolated-worktrees",
		],
		commandResult: { code: 0, stdout: "run ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "run action with poll forever",
		request: {
			action: "run",
			allProjects: true,
			pollForever: true,
		},
		expectedArgs: ["devos", "run", "--all-projects", "--poll-forever"],
		commandResult: { code: 0, stdout: "run forever ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "status action maps non-zero exit to failed result",
		request: {
			action: "status",
			projectId: "default",
			issueKey: "ROY-122",
		},
		expectedArgs: [
			"devos",
			"status",
			"--project",
			"default",
			"--issue",
			"ROY-122",
		],
		commandResult: { code: 1, stdout: "", stderr: "status failed" },
		expectedStatus: "failed",
		expectedError: "status failed",
	},
	{
		name: "onboard action with check flag",
		request: { action: "onboard", check: true },
		expectedArgs: ["devos", "onboard", "--check"],
		commandResult: { code: 0, stdout: "onboard ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "skills list action",
		request: { action: "skills", skillsAction: "list", projectId: "api" },
		expectedArgs: ["devos", "skills", "list", "--project", "api"],
		commandResult: { code: 0, stdout: "skills list ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "skills add action",
		request: {
			action: "skills",
			skillsAction: "add",
			title: "Backend Standard",
			description: "Rules",
			content: "Use consistent module boundaries.",
			projectId: "api",
		},
		expectedArgs: [
			"devos",
			"skills",
			"add",
			"--title",
			"Backend Standard",
			"--description",
			"Rules",
			"--content",
			"Use consistent module boundaries.",
			"--project",
			"api",
		],
		commandResult: { code: 0, stdout: "skills add ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "skills update action",
		request: {
			action: "skills",
			skillsAction: "update",
			name: "backend-standard",
			description: "Updated description",
		},
		expectedArgs: [
			"devos",
			"skills",
			"update",
			"backend-standard",
			"--description",
			"Updated description",
		],
		commandResult: { code: 0, stdout: "skills update ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "skills remove action",
		request: {
			action: "skills",
			skillsAction: "remove",
			name: "backend-standard",
			projectId: "default",
		},
		expectedArgs: [
			"devos",
			"skills",
			"remove",
			"backend-standard",
			"--project",
			"default",
		],
		commandResult: { code: 0, stdout: "skills remove ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "task create action with optional fields",
		request: {
			action: "task",
			taskAction: "create",
			request: "Build a better setup flow",
			projectId: "default",
			nonInteractive: true,
			maxClarificationRounds: 2,
			clarificationAnswers: [{ question: "Who?", answer: "CLI users" }],
			json: true,
		},
		expectedArgs: [
			"devos",
			"task",
			"create",
			"--request",
			"Build a better setup flow",
			"--project",
			"default",
			"--non-interactive",
			"--max-clarification-rounds",
			"2",
			"--json",
			"--clarifications-json",
			'[{"question":"Who?","answer":"CLI users"}]',
		],
		commandResult: { code: 0, stdout: "task ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "task create forces non-interactive flag when omitted",
		request: {
			action: "task",
			taskAction: "create",
			request: "Build task flow",
		},
		expectedArgs: [
			"devos",
			"task",
			"create",
			"--request",
			"Build task flow",
			"--non-interactive",
		],
		commandResult: { code: 0, stdout: "task minimal ok", stderr: "" },
		expectedStatus: "succeeded",
	},
];
